<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="EditEvent.aspx.cs" Inherits="Organizer_EditEvent" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="title" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="title" HeaderText="title" ReadOnly="True" SortExpression="title" />
            <asp:BoundField DataField="participants" HeaderText="participants" SortExpression="participants" />
            <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
            <asp:BoundField DataField="image" HeaderText="image" SortExpression="image" />
            <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
        </Columns>
    </asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT * FROM [EVENT]" 
        UpdateCommand="UPDATE [EVENT] SET [participants] = @participants, [date] = @date, [image] = @image, [description] = @description WHERE [title] = @title"
        DeleteCommand="DELETE FROM [EVENT] WHERE [title] = @title">
    <UpdateParameters>
        <asp:Parameter Name="title" Type="String" />
        <asp:Parameter Name="participants" Type="Int32" />
        <asp:Parameter Name="date" Type="DateTime" />
        <asp:Parameter Name="image" Type="String" />
        <asp:Parameter Name="description" Type="String" />
    </UpdateParameters>
  </asp:SqlDataSource>  
    </asp:Content>

